# Generated by Django 5.1.4 on 2025-03-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('levels', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('question_mark', models.PositiveIntegerField()),
                ('extras', models.PositiveIntegerField()),
                ('questions', models.ManyToManyField(blank=True, related_name='divisions', to='Questions.question')),
            ],
            options={
                'db_table': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('academic_year', models.CharField(max_length=10)),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('divisions', models.ManyToManyField(related_name='question_papers', to='Questions.division')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='Users.subject')),
            ],
            options={
                'db_table': 'Question Papers',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('unit_title', models.CharField(max_length=255)),
                ('co', models.PositiveIntegerField(default=0)),
                ('co_title', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='question_sets', to='Questions.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='Users.subject')),
            ],
            options={
                'db_table': 'Question Sets',
            },
        ),
    ]
