# Generated by Django 5.1.4 on 2025-03-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='status',
            field=models.CharField(default='Incomplete', max_length=100),
        ),
    ]
