# Generated by Django 5.1.4 on 2025-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_questionpaper_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='date',
            new_name='exam_date',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='time',
            new_name='exam_time',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='title',
            new_name='paper_title',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='type',
            new_name='paper_type',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='marks',
            new_name='total_marks',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='division',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
