# Generated by Django 5.1.4 on 2025-03-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_rename_date_questionpaper_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='status',
            field=models.CharField(default='Incomplete', max_length=100),
        ),
    ]
